version: '3.0'

services:
  grafana:
    container_name: 'agora-map-panel'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.5.3}
    ports:
      - 3020:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/agora-map-panel
      - ./provisioning:/etc/grafana/provisioning
